# Generated by Django 5.0.7 on 2024-07-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='view_count',
        ),
    ]
